let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Resin Letter Key Ring",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image2.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Glow in the Dark Bracelet",
    price: 1550,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image4.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Drop Beaded Earrings",
    price: 1500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image5.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Beaded Necklace",
    price: 1500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image6.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Black Sand Ring",
    price: 2500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image31.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Siler Unisex Ring",
    price: 1000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image34.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Drop Beaded Earrings-hoop",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image51.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Beaded Anklets",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image61.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Beaded Waistbeads",
    price: 1500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image73.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Reversible Silk Bonnets",
    price: 1500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/image82.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Concrete Planter",
    price: 4000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/planter3.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Concrete Leaf Planter",
    price: 3000,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/planter6.jpg",
  },
];
